export const PLAYER_CONFIG = {
	ACCELERATION: 20,
	MAX_HORIZONTAL_SPEED: 50,
	MAX_VERTICAL_SPEED: 500,
	DRAG: 10,
	GRAVITY: 5,
	JUMP_FORCE: 250,
	HEIGHT: 74,
	WIDTH: 64,
};

export const WORLD_CONFIG = {
	CELL_SIZE: 64,
};

export const ROOM_CONFIG = {
	MAX_PLAYERS: 8,
};
