export const PLAYER_CONFIG = {
	ACCELERATION: 40,
	MAX_HORIZONTAL_SPEED: 100,
	MAX_VERTICAL_SPEED: 500,
	DRAG: 10,
	GRAVITY: 5,
	JUMP_FORCE: 250,
	HEIGHT: 74,
	WIDTH: 64,
	GROUND_DETECTON_OFFSET: 1,
};

export const WORLD_CONFIG = {
	CELL_SIZE: 64,
};

export const ROOM_CONFIG = {
	MAX_PLAYERS: 8,
};

export const PUSHABLE_CONFIG = {
	DRAG: 10,
	GRAVITY: PLAYER_CONFIG.GRAVITY,
	GROUND_DETECTON_OFFSET: PLAYER_CONFIG.GROUND_DETECTON_OFFSET,
};
